// apps/dstestbed/src/app/carbon.tsx
import React, { ReactElement, useRef } from 'react';
import { Button, TextInput } from '@carbon/react';
import TextField from '@mui/material/TextField';
import { calculatePeriod } from '../lib/calcs';
export function Carbon(): ReactElement {
  const semiMajorRef = useRef();

  const calculateOrbit = () => {
    const semimajor = semiMajorRef.current.value;
    console.log(semimajor);
    const p = calculatePeriod(semimajor);
    console.log(p);
    return p;
  };
  return (
    <>
      <div>Material UI</div>
      <div id="gravity">
        <h2>Kepler's Third Law</h2>
        <div>
          <TextInput
            labelText="Semimajor Axis (AU):"
            type="number"
            id="semimajor"
            placeholder="e.g. 1 for Earth"
            ref={semiMajorRef}
          ></TextInput>
        </div>
        <Button onClick={calculateOrbit}>Calculate Orbital Period</Button>
      </div>
    </>
  );
}

// apps/dstestbed-vue/src/views/Carbon.vue
<script setup lang="ts">
import { ref } from 'vue';
import { calculatePeriod } from '../lib/calcs';

const semimajor = ref('');

function calc() {
  const a = semimajor.value;
  console.log(a);
  console.log(calculatePeriod(a));
}
</script>

<template>
  <main>
    <h1 class="text-h1">Carbon (Vue Native)</h1>
    <div id="gravity">
      <h2 class="text-h2">Kepler's Third Law</h2>
      <div>
        <cv-text-input
          label="Distance in AU"
          v-model="semimajor"
        ></cv-text-input>
        <cv-button kind="primary" default="Primary" @click="calc"
          >Calculate Orbital Period</cv-button
        >
      </div>
    </div>
  </main>
</template>
